### ISSUE TITLE
Running "finish" fails

### ISSUE THREAD

**Issue by 63990** [milliams/cluster-in-the-cloud#3]
I'm using an older version of CitC (initially forked ~6 months ago, but keep up to date until 15th March 2019) and a forked ansible script (last updated 15th March 2019).

Using this configuration, I get the following error when I run 'finish'
```
[opc@mgmt ~]$ ./finish  
ERROR! the playbook: finalise.yml could not be found 

############################################# 
Error: Ansible run did not complete correctly 
############################################# 
```

I tried running a fresh pull (so using the default playbook too) and now get the error
```
[opc@mgmt ~]$ ./finish  
Error: Could not find limits.yaml 
Please create the file and rerun this script. 
```

**Comment by 63990** [comment]
Sorry, I posted a replica issue here https://github.com/ACRC/oci-cluster-terraform/issues/24

**Comment by milliams** [comment]
The error you are seeing is because you have to create that file yourself, [as described in the docs](https://cluster-in-the-cloud.readthedocs.io/en/latest/finalise.html#setting-service-limits). You need to create a file called `limits.yaml` with contents something like:

```yaml
VM.Standard2.1:
  1: 1
  2: 1
  3: 1
VM.Standard2.2:
  1: 1
  2: 1
  3: 1
```

which describes how many of each shape you have available in each AD.

I have added an extra part to that message to point to the relevant part of the docs.
